services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-backend_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./web:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - super-backend
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: super-backend_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - super-backend
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: super-backend_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: super_backend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: super_backend
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - super-backend

networks:
  super-backend:
    driver: bridge

